# Generated by Django 4.2.20 on 2025-04-09 21:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="اسم وصفي للمهمة (مثلاً: إرسال النشرة الإخبارية).",
                        max_length=255,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="أولوية المهمة (قيمة أعلى تعني أولوية أعلى، يتطلب دعم الوسيط).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "معلقة"),
                            ("in_progress", "قيد التنفيذ"),
                            ("completed", "اكتملت"),
                            ("failed", "فشلت"),
                        ],
                        default="pending",
                        help_text="الحالة الحالية للمهمة (معلقة، قيد التنفيذ، مكتملة، فشلت).",
                        max_length=20,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="عدد المرات التي تمت فيها إعادة محاولة المهمة بعد الفشل.",
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3,
                        help_text="الحد الأقصى لعدد مرات إعادة المحاولة المسموح بها للمهمة.",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="الوقت المجدول لتنفيذ المهمة (إذا كانت مؤجلة).",
                        null=True,
                    ),
                ),
                (
                    "last_attempt_time",
                    models.DateTimeField(
                        blank=True, help_text="وقت آخر محاولة لتنفيذ المهمة.", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="رسالة الخطأ في حال فشل المهمة.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="وقت إنشاء سجل المهمة."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="وقت آخر تحديث لسجل المهمة."
                    ),
                ),
                (
                    "permanently_failed",
                    models.BooleanField(
                        default=False,
                        help_text="يشير إلى ما إذا كانت المهمة قد فشلت نهائيًا بعد كل المحاولات.",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="وقت بدء تنفيذ المهمة الفعلي.", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="وقت اكتمال المهمة بنجاح.", null=True
                    ),
                ),
                (
                    "execution_duration",
                    models.DurationField(
                        blank=True,
                        help_text="المدة المستغرقة لتنفيذ المهمة (من البدء إلى الاكتمال).",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeadLetterQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        help_text="معرف المهمة في Celery.", max_length=255
                    ),
                ),
                (
                    "task_name",
                    models.CharField(help_text="اسم المهمة.", max_length=255),
                ),
                (
                    "error_message",
                    models.TextField(help_text="رسالة الخطأ التي تسببت في فشل المهمة."),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="تتبع الاستدعاء للخطأ (Traceback).",
                        null=True,
                    ),
                ),
                (
                    "args",
                    models.TextField(
                        blank=True,
                        help_text="وسائط المهمة (عادةً بصيغة JSON).",
                        null=True,
                    ),
                ),
                (
                    "kwargs",
                    models.TextField(
                        blank=True,
                        help_text="وسائط المهمة المسماة (عادةً بصيغة JSON).",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="وقت إضافة المهمة إلى قائمة انتظار الرسائل الميتة.",
                    ),
                ),
                (
                    "reprocessed",
                    models.BooleanField(
                        default=False, help_text="هل تمت إعادة معالجة المهمة؟"
                    ),
                ),
                (
                    "reprocessed_at",
                    models.DateTimeField(
                        blank=True, help_text="وقت إعادة معالجة المهمة.", null=True
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False, help_text="هل تم إرسال إشعار بفشل المهمة؟"
                    ),
                ),
                (
                    "original_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="المهمة الأصلية التي فشلت.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dead_letter_entries",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة فاشلة (DLQ)",
                "verbose_name_plural": "المهام الفاشلة (DLQ)",
                "ordering": ["-created_at"],
            },
        ),
    ]
