# Generated by Django 5.1.4 on 2025-04-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="وقت إنشاء سجل المهمة."
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="رسالة الخطأ في حال فشل المهمة.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="last_attempt_time",
            field=models.DateTimeField(
                blank=True, help_text="وقت آخر محاولة لتنفيذ المهمة.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="max_retries",
            field=models.IntegerField(
                default=3,
                help_text="الحد الأقصى لعدد مرات إعادة المحاولة المسموح بها للمهمة.",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="أولوية المهمة (قيمة أعلى تعني أولوية أعلى، يتطلب دعم الوسيط).",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="retry_count",
            field=models.IntegerField(
                default=0,
                help_text="عدد المرات التي تمت فيها إعادة محاولة المهمة بعد الفشل.",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True,
                help_text="الوقت المجدول لتنفيذ المهمة (إذا كانت مؤجلة).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="الحالة الحالية للمهمة (قيد الانتظار، قيد التنفيذ، مكتملة، فشلت).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="task_name",
            field=models.CharField(
                help_text="اسم وصفي للمهمة (مثلاً: إرسال النشرة الإخبارية).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="وقت آخر تحديث لسجل المهمة."
            ),
        ),
    ]
