# Generated by Django 5.1.4 on 2025-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_job_created_at_alter_job_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="permanently_failed",
            field=models.BooleanField(
                default=False,
                help_text="يشير إلى ما إذا كانت المهمة قد فشلت نهائيًا بعد كل المحاولات.",
            ),
        ),
    ]
