# Generated by Django 4.2.20 on 2025-04-07 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_job_permanently_failed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadLetterQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        help_text="معرف المهمة في Celery.", max_length=255
                    ),
                ),
                (
                    "task_name",
                    models.CharField(help_text="اسم المهمة.", max_length=255),
                ),
                (
                    "error_message",
                    models.TextField(help_text="رسالة الخطأ التي تسببت في فشل المهمة."),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True, help_text="تتبع الاستدعاء للخطأ.", null=True
                    ),
                ),
                (
                    "args",
                    models.TextField(blank=True, help_text="وسائط المهمة.", null=True),
                ),
                (
                    "kwargs",
                    models.TextField(
                        blank=True, help_text="وسائط المهمة المسماة.", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="وقت إضافة المهمة إلى قائمة انتظار الرسائل الميتة.",
                    ),
                ),
                (
                    "reprocessed",
                    models.BooleanField(
                        default=False, help_text="ما إذا تمت إعادة معالجة المهمة."
                    ),
                ),
                (
                    "reprocessed_at",
                    models.DateTimeField(
                        blank=True, help_text="وقت إعادة معالجة المهمة.", null=True
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False, help_text="ما إذا تم إرسال إشعار بفشل المهمة."
                    ),
                ),
                (
                    "original_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="المهمة الأصلية التي فشلت.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dead_letter_entries",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة فاشلة",
                "verbose_name_plural": "المهام الفاشلة",
                "ordering": ["-created_at"],
            },
        ),
    ]
