# Generated by Django 4.2.20 on 2025-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_deadletterqueue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deadletterqueue",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "مهمة فاشلة (DLQ)",
                "verbose_name_plural": "المهام الفاشلة (DLQ)",
            },
        ),
        migrations.AddField(
            model_name="job",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="وقت اكتمال المهمة بنجاح.", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="execution_duration",
            field=models.DurationField(
                blank=True,
                help_text="المدة المستغرقة لتنفيذ المهمة (من البدء إلى الاكتمال).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="started_at",
            field=models.DateTimeField(
                blank=True, help_text="وقت بدء تنفيذ المهمة الفعلي.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="deadletterqueue",
            name="args",
            field=models.TextField(
                blank=True, help_text="وسائط المهمة (عادةً بصيغة JSON).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="deadletterqueue",
            name="kwargs",
            field=models.TextField(
                blank=True,
                help_text="وسائط المهمة المسماة (عادةً بصيغة JSON).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deadletterqueue",
            name="notification_sent",
            field=models.BooleanField(
                default=False, help_text="هل تم إرسال إشعار بفشل المهمة؟"
            ),
        ),
        migrations.AlterField(
            model_name="deadletterqueue",
            name="reprocessed",
            field=models.BooleanField(
                default=False, help_text="هل تمت إعادة معالجة المهمة؟"
            ),
        ),
        migrations.AlterField(
            model_name="deadletterqueue",
            name="traceback",
            field=models.TextField(
                blank=True, help_text="تتبع الاستدعاء للخطأ (Traceback).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "معلقة"),
                    ("in_progress", "قيد التنفيذ"),
                    ("completed", "اكتملت"),
                    ("failed", "فشلت"),
                ],
                default="pending",
                help_text="الحالة الحالية للمهمة (معلقة، قيد التنفيذ، مكتملة، فشلت).",
                max_length=20,
            ),
        ),
    ]
