version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: redis_server
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always

volumes:
  redis_data:
