@echo off
echo Stopping any running Celery workers...
taskkill /f /im celery.exe 2>nul
echo.

echo Restarting Redis (if using Docker)...
docker-compose restart redis
echo.

echo Installing/updating dependencies...
pip install -r requirements.txt
echo.

echo Stopping any running Redis containers...
docker-compose stop redis
echo Starting Redis...
docker-compose up -d redis
echo Waiting for Redis to start...
timeout /t 5

echo Starting Celery worker with priority support...
celery -A task_queue_project worker --loglevel=info -P solo --without-heartbeat --without-gossip --without-mingle --concurrency=1
